# -- Habilitar la interfaz enp0s3 y crear Adaptador puente --
# Ves a la configuración de la máquina virtual, subapartado “Red” y selecciona la opción “Adaptador puente”.
# vi /etc/sysconfig/network-scripts/ifcfg-enp0s3
# Modifica la opción de “ONBOOT=no” a “ONBOOT=yes” y guarda los cambios.
# service network restart
# ----

# -- Instalación de SSH --
# yum –y install openssh-server openssh-clients
# systemctl start sshd
# systemctl enable sshd
# ----

# -- Instlación de Ansible --
# yum -y install epel-release
# yum -y install ansible
# yum -y update
# ----

# -- Generación de una clave SSH que punta al mismo ordenador --
# ssh-keygen
# Pulsa enter y introduce una frase.
# ssh-copy-id root@{ip}
# vi /etc/ansible/hosts
# En caso de que no funcione:
# ssh-copy-id -i root@{ip}
# ansible all -m ping -vvv
# Añade la IP del ordenador al que quieres apuntar
# mkdir Ansible
# ----

# -- Comando para instalar el playbook --
# ansible-playbook tools.yaml --extra-vars "ip=10.0.2.15"
# ----

# -- Herramientas instaladas --
#  git
#  JDK 16
#  Docker
#  Docker Compose
#  Helm
#  Kubernetes
#  Nexus 3
#  Jenkins
#  Maven
#  Python 3
#  SonarQube
# ----
---
- name: Iniciando el entorno
  hosts: tools
  tasks:

  - name: Instalacion de Git
    yum:
      name: git
      state: present

  - name: Se crea una carpeta para las descargas
    ansible.builtin.file:
      path: /descargas
      state: directory

  - name: Instalando Wget
    yum:
      name: wget
      state: present

  - name: Instalando Java 11
    yum:
      name: java-11-openjdk-devel
      state: present

  - name: Instalando Curl
    yum:
      name: curl
      state: present

  - name: Instalando Docker
    yum:
      name: docker
      state: present

  - name: Descargando Docker-Compose
    shell: curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

  - name: Añadiendo los permisos a Docker-Compose
    shell: chmod +x /usr/local/bin/docker-compose

  - name: Iniciando servicio de Docker
    shell: systemctl start docker

  - name: Habilitando el servicio de arranque de Docker
    shell: systemctl enable docker

  - name: Instalando httpd
    yum:
      name: httpd
      state: present

  - name: Iniciando el servicio httpd
    ansible.builtin.systemd:
      name: httpd
      state: started
      enabled: yes

  - name: Creando carpeta para Kubernetes
    ansible.builtin.file:
      path: /kubernetes
      state: directory

  - name: Configurandio el repositorio de Kubernetes
    shell: |
      cat <<EOF > /etc/yum.repos.d/kubernetes.repo
      [kubernetes]
      name=Kubernetes
      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      EOF

  - name: Instalando kubelet
    yum:
      name: kubelet-1.20.0-0
      state: present

  - name: Instalando kubeadm
    yum:
      name: kubeadm-1.20.0-0
      state: present

  - name: Instalando kubectl
    yum:
      name: kubectl-1.20.0-0
      state: present

  - name: Iniciando el servicio kubelet y habilitandolo
    ansible.builtin.systemd:
      name: kubelet
      state: started
      enabled: yes

  - name: Configurando la red
    shell: |
      cat <<EOF > /etc/sysctl.d/k8s.conf
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      EOF

  - name: Se modifica el kernel
    shell: sysctl --system

  - name: Se desactiva Selinux
    shell: setenforce 0

  - name: Se configura Selinux
    shell: sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config

  - name: Se configura fstab
    shell: sed -i '/swap/d' /etc/fstab

  - name: Se desactiva swap
    shell: swapoff -a

  - name: Creando el cluster de kubernetes
    shell: kubeadm init --apiserver-advertise-address={{ ip }} --pod-network-cidr=10.244.0.0/16
    ignore_errors: yes

  - name: Se crea un directorio para el archivo de configuracion de Kubernetes
    ansible.builtin.file:
      path: ~/kube
      state: directory

  - name: Se crea la carpeta del archivo de configuración de Kubernetes
    shell: mkdir -p  ~/.kube

  - name: Se copia el archivo de configuracion a la ruta anterior
    shell: cp -u /etc/kubernetes/admin.conf ~/.kube/config

  - name: Se aplican los cambios de red a Kubernetes
    shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"

  - name: El nodo maestro ahora puede ser un nodo trabajador
    shell: kubectl taint nodes --all node-role.kubernetes.io/master-
    ignore_errors: yes

  - name: Instalando kubernetes-metrics
    shell: kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml

  - name: Deteniendo Docker
    shell: systemctl stop docker

  - name: Deteniendo kubelet
    shell: systemctl stop kubelet

  - name: Purgando iptable I
    shell: iptables --flush

  - name: Purgando iptable II
    shell: iptables -tnat --flush

  - name: Iniciando kubelete
    shell: systemctl start kubelet

  - name: Iniciando Docker
    shell: systemctl start docker

  - name: Creando el alias k=kubectl
    lineinfile:
      path: ~/.bashrc
      line: alias k='kubectl'
      insertbefore: BOF

  - name: Creando el alias ksys=kubectl -n kube-sys
    lineinfile:
      path: ~/.bashrc
      line: alias k='kubectl -n kube-system'
      insertbefore: BOF

  - name: Creano carpeta para Helm
    shell: mkdir -p /Helm

  - name: Descargando Helm 3
    shell: curl -fsSL -o /Helm/get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3

  - name: Otorgando permisos al instaldor
    shell: chdir=/Helm chmod 700 get_helm.sh

  - name: Ejecutando el script
    shell: chdir=/Helm ./get_helm.sh

  - name: Creando carpeta para los yml de Kubernetes
    shell: mkdir -p /kubernetes

  - name: Descargando el volumen persistente de nexus 3
    shell: chdir=/kubernetes curl -o ./nexus3-pv.yml "https://raw.githubusercontent.com/MartiMarch/Kubernetes/main/nexu3/nexus3-pv.yml"

  - name: Descargando la reclamacion de volumen persistente de nexus 3
    shell: chdir=/kubernetes curl -o ./nexus3-pvc.yml "https://raw.githubusercontent.com/MartiMarch/Kubernetes/main/nexu3/nexus3-pvc.yml"

  - name: Descargando el servicio de nexus 3
    shell: chdir=/kubernetes curl -o ./nexus3-service.yaml "https://raw.githubusercontent.com/MartiMarch/Kubernetes/main/nexu3/nexus3-service.yaml"

  - name: Descargando el deployment de nexus 3
    shell: chdir=/kubernetes curl -o ./nexus3-deployment.yaml "https://raw.githubusercontent.com/MartiMarch/Kubernetes/main/nexu3/nexus3-deployment.yaml"

  - name: Creando el nombre de espacios para nexus3
    shell: kubectl create namespace nexus3
    ignore_errors: yes

  - name: Cargando el volumen persistente de Nexus 3
    shell: chdir=/kubernetes kubectl -n nexus3 apply -f nexus3-pv.yml

  - name: Cargando la reclamación de volumen persistente de Nexus 3
    shell: chdir=/kubernetes kubectl -n nexus3 apply -f nexus3-pvc.yml

  - name: Cargando el serivio de red de Nexus 3
    shell: chdir=/kubernetes kubectl -n nexus3 apply -f nexus3-service.yaml

  - name: Cargando el Deployment de Nexus 3
    shell: chdir=/kubernetes kubectl -n nexus3 apply -f nexus3-deployment.yaml

  - name: Creando el nombre de espacios para SonarQube
    shell: kubectl create namespace sonar
    ignore_errors: yes

  - name: Descargando el volumen persistente deSonarQube
    shell: chdir=/kubernetes curl -o ./sonar-pv.yml "https://raw.githubusercontent.com/MartiMarch/Kubernetes/main/sonar/sonar-pv.yml"

  - name: Descargando la reclamacion de volumen persistente
    shell: chdir=/kubernetes curl -o ./sonar-pvc.yml "https://raw.githubusercontent.com/MartiMarch/Kubernetes/main/sonar/sonar-pvc.yml"

  - name: Descargando el servicio de SonarQube
    shell: chdir=/kubernetes curl -o ./sonar-service.yaml "https://raw.githubusercontent.com/MartiMarch/Kubernetes/main/sonar/sonar-service.yaml"

  - name: Descargando el deployment de SonarQube
    shell: chdir=/kubernetes curl -o ./sonar-deployment.yaml "https://raw.githubusercontent.com/MartiMarch/Kubernetes/main/sonar/sonar-deployment.yaml"

  - name: Cargando el volumen persistente de SonarQube
    shell: chdir=/kubernetes kubectl -n sonar apply -f sonar-pv.yml

  - name: Cargando la reclamacion de volumen persistente de SonarQube
    shell: chdir=/kubernetes kubectl -n sonar apply -f sonar-pvc.yml

  - name: Cargando el servicio de SonarQube
    shell: chdir=/kubernetes kubectl -n sonar apply -f sonar-service.yaml

  - name: Cargando el deployment de SonarQube
    shell: chdir=/kubernetes kubectl -n sonar apply -f sonar-deployment.yaml

  - name: Instalando Python 3
    yum:
      name: python3
      state: present

  - name: Instalacion de Maven
    yum:
      name: maven
      state: present

  - name: Habilitando el repositorio de Jenkins
    shell: curl --silent --location http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo > /etc/yum.repos.d/jenkins.repo

  - name: Añadiendo el repositorio al sistema
    shell: rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key

  - name: Instalando Daemonize
    yum:
      name: daemonize
      state: present

  - name: Instalando jenkins.noarch
    shell: yum -y install jenkins.noarch --nogpgcheck

  - name: Instalando Jenkins
    yum:
      name: jenkins
      state: present

  - name: Iniciando el servicio de Jenkins
    shell: systemctl start jenkins

  - name: Habilitando el servicio de Jenkins en el arranque
    shell: systemctl enable jenkins

  - name: Abriendo el puerto 8080
    shell: firewall-cmd --permanent --zone=public --add-port=8080/tcp

  - name: Reiniciando el firewall
    shell: firewall-cmd --reload
